### ISSUE TITLE
simple is good but not enough

### ISSUE THREAD

**Issue by dotkt** [Ybalrid/kissnet#12]
i love your kissnet.
i cant agree more with you.
Asio is too complex.what Asio to small network application is nearlly using bazooka to kill a mosquito.
but there are some questions:
how to set timeout parameter?
how to close the connect ?
is it thread safe?
i love your idea very much soryy about my poor English.

**Comment by cpz** [comment]
Its totally thread safe, tested by myself, running like 1000 threads each using KissNET, no problems.

Closing connection - easiest way:
```C+
kn::tcp_ssl_socket server_socket(kn::endpoint("cpz.github.io:443"));
server_socket.Close(); // Closes connection.
```

What you mean by Timeout param?

**Comment by Ybalrid** [comment]
I'm all for ideas to improve this @dotkt! 

It's currently just a small subset of a socket library, it only has the most minimal functionality right now.

**Comment by dotkt** [comment]
it's nice idea it will be a great lib
