### ISSUE TITLE
Direct compilation with clang on Windows

### ISSUE THREAD

**Issue by h5rdly** [Ybalrid/kissnet#14]
Hi,

First of all, this is awesome. This library should've been made years ago!

Pardon my noobness, I installed OpenSSL on windows from [here](https://slproweb.com/products/Win32OpenSSL.html). 

Now cmake finds it and works fine, but I'm trying to compile with clang, since I'm not using cmake in my project currently.

Is it somehow possible to make the compilation on Windows via a direct clang (10) command?

Thanks,
Eli

**Comment by Ybalrid** [comment]
@h5rdly This library is just a single header file. Just paste kissnet.hpp in your folder and #include it

**Comment by h5rdly** [comment]
@Ybalrid  But I need to compile and link against OpenSSL :)

On Windows, it seems to work for me via:

`clang -std=c++2a -I C:\OpenSSL\include -L C:\OpenSSL\lib\*.lib kissnet.cpp`

Where `C:\OpenSSL` is where I installed OpenSSL from the above link

**Comment by Ybalrid** [comment]
In that case it's an OpenSSL issue. And I am glad you got it working 😃
