### ISSUE TITLE
Double free when moved

### ISSUE THREAD

**Issue by zhiayang** [Ybalrid/kissnet#15]
When either the move constructor or move-assign operator is called, we do:
```
this->getaddrinfo_results = std::move(other.getaddrinfo_results);
```

unfortunately, `std::move` does not set the moved-from pointer (ie. `other.getaddrinfo_results`) to null; when the rvalue is destructed after being moved from, it will call `freeaddrinfo()` on the result which has been moved.

When the "real" socket is then destructed, it will call `freeaddrinfo()` again on the same result pointer, leading to a double-free.

**Comment by Ybalrid** [comment]
Indeed, thanks for finding the bug

**Comment by Ybalrid** [comment]
As you can guess, this project could use more testing. 😄
