### ISSUE TITLE
replace "kissnet::error::handle" with "kissnet::error::handler"

### ISSUE THREAD

**Issue by xyzlxw** [Ybalrid/kissnet#2]
Hi,

Please check the file kissnet.hpp at Ln 109,  this may need to replace "kissnet::error::handle" with "kissnet::error::handler".   

Regards,
Evan

**Comment by Ybalrid** [comment]
Actually, it should be "handle"a as the verb ( = action ) "to handle". But good catch!

The function definition has been fixed in latest commit
