### ISSUE TITLE
kissnet::tcp_ssl_socket is available when KISSNET_USE_OPENSSL is undefined

### ISSUE THREAD

**Issue by cmdremily** [Ybalrid/kissnet#41]
It's possible to instantiate a non-functioning tcp_ssl_socket when KISSNET_USE_OPENSSL  is not defined, this is confusing and lead me to waste quite some time debugging why the socket didn't do anything.

**Comment by Ybalrid** [comment]
Bit busy right now but @cmdremily can you wrap the `using` directive in a `#ifdef KISSNET_USE_OPENSSL` block and submit a pull request? I would merge this in right away and that would fix this paper-cut 😄
