### ISSUE TITLE
Rename to...

### ISSUE THREAD

**Issue by untyper** [Ybalrid/kissnet#47]
**K**eep **I**t **S**tupid **S**imple **NET**work

I find myself attacked by the current name. It's as if the name of the library is picking a fight with me by calling **me** stupid. How dare it!! Buut it's arguable I guess... since I am here bothered by the order of some words in a library I don't even own...

"**S**tupid" describes how "**S**imple" it is, so it would be more fitting to swap their places.
The acronym would still remain the same, so there should not be any major issues either.

**Comment by Ybalrid** [comment]
K.I.S.S. is a well-known acronym for referring to the concept of not complicating things. It is not meant as a personal attack on anybody https://en.wikipedia.org/wiki/KISS_principle

Tho, to be specific, the actual name of the library is just "kissnet", the sub-line is just an explanation of what the name means, but really it's a "network library that tries to follow a KISS principle design"
