### ISSUE TITLE
How to bind to UDP multicast

### ISSUE THREAD

**Issue by anselanza** [Ybalrid/kissnet#50]
I am writing an application that needs to receive UDP packets which are sent via UD multicast.

Using WireShark, I can see that the packets are being received on a particular interface, with the destination `236.10.10.10` which I believe is a multicast address. However, no UDP packets are received when I init as follows:

```
 kn::udp_socket b_socket(kn::endpoint("0.0.0.0", 56565));
 b_socket.bind();
```

I'm a little rusty on multicasting... Is there another function I need to call or a different flag that needs to be set in order to receive UDP multicast using this library?

**Comment by andersc** [comment]
I did just pull request a UDP join multicast solution.

https://github.com/Ybalrid/kissnet/pull/51

Guess you can see it as a candidate before merged but please try it out. Will add leave multicast also. See the included example code.

/A

**Comment by anselanza** [comment]
Ah, this looks perfect! 

Thanks, I'm going to try out the forked version now!

**Comment by anselanza** [comment]
Can confirm this works great!

**Comment by andersc** [comment]
Cool.. Thanks for checking!

@Ybalrid please let me know if you're OK with th PR or if you want me to change something. 

/A

**Comment by anselanza** [comment]
Hmm @andersc I'm noticing that things aren't working as expected when I test with data coming from an interface (e.g. `en01` or whatever) that isn't localhost. Is the socket being re-assigned to a different endpoint IP address or interface in your `join` function somewhere?

**Comment by andersc** [comment]
Hi,

No the join method is creating its own socket. Will create a project sending from one separate machine to another over a local network. Will do that later today and post the link to that project here.

/A

**Comment by andersc** [comment]
Works for me ->

https://github.com/andersc/multicast_test

I run the sender on one computer and the receiver on another.. and I get the multicast packets with the correct payload at the correct intervals.

Have you really verified your set-up?

(BTW I use IPv4)

/Anders.

**Comment by anselanza** [comment]
Interesting! And thank you for taking the time to test this out so thoroughly.

I'm still not receiving packets, though.

In WireShark, I can clearly see the data I'm interested in:
<img width="838" alt="Screenshot 2022-02-03 at 09 41 29" src="https://user-images.githubusercontent.com/3015222/152309920-c102ef14-4331-49c5-ab31-abf9f35de0c3.png">

As you can see, in my case I'm receiving data on interface `en14` (as expected), where the multicast group is `236.10.10.10` and the port is `56565`. In my code, as far as I can tell, I'm using exactly these details:

<img width="827" alt="Screenshot 2022-02-03 at 09 41 52" src="https://user-images.githubusercontent.com/3015222/152310156-d1e877b9-8112-4a2b-9240-833666d39876.png">

And further down, I try to receive data on this socket:
<img width="596" alt="Screenshot 2022-02-03 at 09 42 52" src="https://user-images.githubusercontent.com/3015222/152310218-0e2904d4-b257-46e6-85ea-0a7d0ccfd99e.png">

But... nothing:
<img width="376" alt="Screenshot 2022-02-03 at 09 50 45" src="https://user-images.githubusercontent.com/3015222/152310295-8f27b76b-e440-4bd6-83f0-0f051e7d265a.png">

I don't believe there's anything wrong with my network setup (especially since WireShark is, indeed, seeing the packets I'm interested in). What am I doing wrong?

**Comment by anselanza** [comment]
Ha. As soon as I turned my Wifi off, it started working.

So... I guess somewhere I need to set the interface properly!

**Comment by andersc** [comment]
Ahh.. nice you're making progress!

I did actually implement this already, I'm unable to test this so it would be great if you do.

So this is how you specify the 'optional specific interface' ->

In your code you -> 

    auto mcast_listen_socket = kissnet::udp_socket();
    mcast_listen_socket.join(kissnet::endpoint(MULTICAST_GROUP, PORT));

If you want to specify in your case 'en14' get the IP of 'en14'. Let's say it's '192.168.0.44'

Then you ->

mcast_listen_socket.join(kissnet::endpoint(MULTICAST_GROUP, PORT), "192.168.0.44");

it might not work and send me back to the drawing board however, please try it out.

/Anders

**Comment by anselanza** [comment]
Hmm, that seems to result in a runtime error, no matter what IP address is in there, either `192.168.11.201` (which is the IP address my ethernet adapter) or `0.0.0.0`:

```
libc++abi: terminating with uncaught exception of type std::runtime_error: setsockopt() failed

[1]    44451 abort      ./psn-tether-agent ledgo-floor 127.0.0.1 true
```

**Comment by anselanza** [comment]
OK, interesting.

It does actually work as expected, sometimes - even with the Wifi connected - but I need to unplug and plug in my ethernet cable after turning Wifi off or on.

So probably something to do with Mac OS stuff.

But this is great! Thank you for all your help!

**Comment by andersc** [comment]
NP!

Will check when I get home on my mac to see if I get the same behaviour. Should work out of the box without playing around with re-plugging cables. However the underlying BSD sockets might need some extra love ;-) 

/Anders
