### ISSUE TITLE
socket `set_non_blocking` breaks if the socket is not non-blocking to begin with

### ISSUE THREAD

**Issue by zhiayang** [Ybalrid/kissnet#52]
If a socket is *not* non-blocking, and you call `set_non_blocking(false)` on it (which should do nothing), what actually happens is that the socket gets *set* to non-blocking! The exact opposite of what you wanted.

The bug is at this line:

https://github.com/Ybalrid/kissnet/blob/7da5b83eadc9a9e2ec0d6d954d799a593f773dd0/kissnet.hpp#L919

If `flags` did not have `O_NONBLOCK`, then this line actually toggles it (turning it on!). What should be written is actually:

```cpp
const auto newflags = state ? (flags | O_NONBLOCK) : (flags & ~O_NONBLOCK);
```

I found this on my very old (2 years?) version, but from the link above, this bug is clearly present in the current version -- I just never noticed it till now.

**Comment by Ybalrid** [comment]
... I think we fixed this, right?  @zhiayang can we close this issue or is the bug still present on your end?

**Comment by zhiayang** [comment]
Yep, this was fixed already! Thanks for fixing it. I think your commit didn't use github's magic keywords that would've closed this issue automatically xD
