### ISSUE TITLE
kissnet.hpp(156,22): warning C4244: '=': conversion from 'int' to 'ADDRESS_FAMILY', possible loss of data

### ISSUE THREAD

**Issue by BullyWiiPlaza** [Ybalrid/kissnet#66]
As the title says, I'm getting the warning
`kissnet.hpp(156,22): warning C4244: '=': conversion from 'int' to 'ADDRESS_FAMILY', possible loss of data`
I'm using `Visual Studio 2022` with the warning level `/W4` switch enabled.

**Comment by Ybalrid** [comment]
It looks like the ADDRESS_FAMILY field in that structure is an `unsigned short`. We're putting an `int` in there for some reason. This is probably harmless.

I need to doublecheck the behavior on other operating systems than windows, otherwise, a simple cast will silence the warning

**Comment by Ybalrid** [comment]
patched out.
