### ISSUE TITLE
examples/udp_ntp_client/main.cpp macOS bugfix 

### ISSUE THREAD

**Issue by camilleg** [Ybalrid/kissnet#67]
On macOS Ventura 13.1, the UDP NTP example hangs infinitely, because `a_socket.bytes_available()` returns not 48 but 80.
This happens with not just time.apple.com but also time.google.com and time.nist.gov.
I tried this with and without my university VPN turned on.

A quick fix is to change `== 48` to `>= 48`.
Then the correct time is printed, and the program runs as expected.

(I'm not sure why the same code on Ubuntu 22.04 gets the expected 48 bytes, or how the NTP server detects the difference.  A few vendor-specific manuals claim that the extra space is for a null-terminated server name, but they don't say that the OS of the client matters, and I couldn't confirm that claim.  But this is not important for kissnet.)

**Comment by Ybalrid** [comment]
I am not the author of that example, and I am not familiar with the inner workings of the NTP protocol... 

If you have a fix for a problem you found, I'll gladly take it. Tho I also have *no idea* why you would get a different number of bytes out of the thing.

Those operating systems have different network stacks (even if it's all BSD-like?), so who knows. It does seem error prone to me to expect to read *exactly 48 bytes* if you could get more out of the system.

**Comment by camilleg** [comment]
The fix is to change `== 48` to `>= 48`.  Would you like me to make a PR for this one-character fix? :)

**Comment by Ybalrid** [comment]
I could press the 2 keystrokes in vim, or I could click a button. You're telling me it makes it work. I don't really have a mac handy to try... 🤣

**Comment by Ybalrid** [comment]
@camilleg off-topic, I am curious, you're using this lib at NCSA? 🙂

**Comment by camilleg** [comment]
Not for my day job, no.  Just to modernize something I wrote for UIUC (but not NCSA) 20 years ago that remains useful, https://github.com/camilleg/clockkit.
