### ISSUE TITLE
You have a leak!

### ISSUE THREAD

**Issue by sjk7** [Ybalrid/kissnet#7]
Hello,
You have a leak because you need to:
<code>
			if (this->getaddrinfo_results)
			{
				::freeaddrinfo(getaddrinfo_results);
			}
</code>

in the destructor
Nice library, thanks!

Steve

**Comment by Ybalrid** [comment]
Hey Steve!

That's a good catch! I'm going to look at it a bit later and fix this, but it you want you can also submit a pull request ;-)
